name: Build

on:
  pull_request:
  push:
    branches:
      - master
      - ci-experiments

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
    steps:
    - uses: actions/checkout@v2
    - name: Install Elan
      run: |
        set -o pipefail
        curl -sSfL https://github.com/leanprover/elan/releases/download/v1.4.2/elan-x86_64-unknown-linux-gnu.tar.gz | tar xz
        ./elan-init -y --default-toolchain none
        echo "$HOME/.elan/bin" >> $GITHUB_PATH
    - name: Build
      run: lake build
    - name: Run tests
      run: ./test
    - name: Release nightly
      if: github.repository == 'JLimperg/aesop' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/ci-experiments')
      env:
          GH_TOKEN: ${{ github.token }}
      run: |
        tar -caf aesop-linux-64.tar.gz -C build .
        gh release create nightly-${{ github.sha }} -R JLimperg/aesop-nightlies --prerelease --notes "" aesop-linux-64.tar.gz
